FROM python:3.12

WORKDIR /regression-app

COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /code/app

COPY ./src ./src
COPY ./app ./app
COPY ./model.pkl .
COPY ./data ./data

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]